In [1]:
import numpy as np
import sys

In [2]:
x = '''
Applications of NumPy:

Mathematics (MATLAB Replacement)
Plotting (Matplotlib)
Backend (Pandas,Connect 4 , Digital Photography)
Machine Learning

'''

In [3]:
# The Basics

In [4]:
a = np.array([2,3,4],dtype = 'int16')
print(a)

[2 3 4]


In [5]:
b = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(b)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [6]:
# Get Dimension
b.ndim

2

In [7]:
# Get Shape
b.shape

(2, 5)

In [8]:
# Get Type
b.dtype
a.dtype

dtype('int16')

In [9]:
# Get Size
a.itemsize
b.itemsize

4

In [10]:
# Get No. of Elements:
b.size

10

In [11]:
# Get Total Size :
b.nbytes
# b.nbytes = b.itemsize(size of 1 element in byte)* b.size(No. of elements)

40

In [12]:
# Accessing/Changing specific elements, rows, columns, etc.

In [13]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [14]:
# Get a specific element [r,c]
c[1,1]

5

In [15]:
# Get a specific row 
c[1,:]

array([4, 5, 6])

In [16]:
# Get a specific column
c[:,2]

array([3, 6])

In [17]:
# Get a little bit more fancy [startindex:endindex:stepsize]
c[1,::2]

array([4, 6])

In [18]:
# Changing values in an array
c[0,2] = 7
c

array([[1, 2, 7],
       [4, 5, 6]])

In [19]:
c[1,:] = [7,8,9]
c

array([[1, 2, 7],
       [7, 8, 9]])

In [20]:
# 3D Array

In [21]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
d[1,1,1]

8

In [23]:
# Changing Values
d[0,:,1] = [5,5]
d

array([[[1, 5],
        [3, 5]],

       [[5, 6],
        [7, 8]]])

In [24]:
d[:,0,:] = [[8,1],[2,6]]
d

array([[[8, 1],
        [3, 5]],

       [[2, 6],
        [7, 8]]])

In [25]:
# Initializing Different Types of Arrays

In [26]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# All 1s matrix
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
# Any other number
np.full((2,2),77)

array([[77, 77],
       [77, 77]])

In [29]:
# Any other number (full_like)(-> it attains the shape of already declared array)
p = np.array([[1,2,3],[4,5,6]])
np.full_like(p,7)
#or
np.full(p.shape,7)

array([[7, 7, 7],
       [7, 7, 7]])

In [30]:
# Random decimal numbers
np.random.rand(4,2)
np.random.random_sample(p.shape)

array([[0.76517984, 0.42969516, 0.95437766],
       [0.39154861, 0.76845964, 0.47826743]])

In [31]:
# Random integer values
np.random.randint(7, size = (3,3))

array([[3, 3, 2],
       [0, 2, 5],
       [5, 5, 0]])

In [32]:
# Identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
# Repeating an Array
arry = np.array([[1,2,3]])
p1 = np.repeat(arry,3,axis = 0)
p1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [34]:
# Be careful when copying arrays!!!
a = np.array([1,2,3])
b = a.copy()
b[1]=7
a

array([1, 2, 3])

In [35]:
# linspace
d = np.linspace(1,10, num = 5)
d

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [36]:
# sort
a = np.array([[3,2,7,1],[9,1,5,2]])
a.sort()
a

array([[1, 2, 3, 7],
       [1, 2, 5, 9]])

In [37]:
# concatenate
a = np.array([1,3,2,5])
b = np.array([2,3,7,4])
c = np.concatenate((a,b))
c

array([1, 3, 2, 5, 2, 3, 7, 4])

In [38]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[3,4,1]])
c = np.concatenate((a,b),axis = 0)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 4, 1]])

In [39]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[3,4,1]])
c = np.concatenate((a,b),axis = 1)
c

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 3, 4, 1]])

In [40]:
# reshape
a = np.arange(8)
a = a.reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
a = np.arange(6)
print(a.shape)
a1 = a[np.newaxis,:] # increases dimension / we can also say make it a row vector
print(a1.shape)
a2 = a[:,np.newaxis] # make it a cols vector
print(a2.shape)

(6,)
(1, 6)
(6, 1)


In [42]:
a = np.arange(6)
a.shape
a1 = np.expand_dims(a,axis = 0) # make it a row vector
a1.shape
a2 = np.expand_dims(a,axis = 1) # make it a col vector
a2.shape

(6, 1)

In [43]:
a = np.array([[[1,2,3],[7,8,9],[1,11,19]],[[1,5,2],[2,4,99],[1,13,25]]])
b = a[(a >= 7) & (a<=25)]
b
# set(b)

array([ 7,  8,  9, 11, 19, 13, 25])

In [44]:
a = np.array([[[1,2,3],[7,8,9],[1,11,19]],[[1,5,2],[2,4,99],[1,13,25]]])
b = a[(a <= 7) | (a>=25)]
b
#set(b)

array([ 1,  2,  3,  7,  1,  1,  5,  2,  2,  4, 99,  1, 25])

In [45]:
b = (a<= 7) | (a>= 25)
b

array([[[ True,  True,  True],
        [ True, False, False],
        [ True, False, False]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]]])

In [46]:
# Converting NumPy arrays to list

In [47]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [48]:
np.arange(0,11,2).tolist()

[0, 2, 4, 6, 8, 10]

In [49]:
# Mathematics

In [50]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
a+2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [52]:
a*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [53]:
a/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ]])

In [54]:
a-2

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6]])

In [55]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
b = np.array([1,2,3,4])

In [57]:
a-b

array([[0, 0, 0, 0],
       [4, 4, 4, 4]])

In [58]:
a**2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [59]:
# Take the sin,cos and tan
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825]])

In [60]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654,  1.15782128],
       [-3.38051501, -0.29100619,  0.87144798, -6.79971146]])

In [61]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003]])

In [62]:
# Linear Algebra

In [63]:
# Matrix Multiplication
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [64]:
# Determinant 
x = np.identity(2)
np.linalg.det(x)
y = np.full_like(x,2)
np.linalg.det(y)

0.0

In [65]:
# likewise we can also find :
# Trace, Singular Vector Decomposition,Eigenvalues,Matrix Norm,
# Inverse, etc.

In [66]:
# Statistics

In [67]:
stats = np.array([[1,2,3,4],[5,6,7,8]])
stats

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
np.min(stats)

1

In [69]:
np.max(stats)

8

In [70]:
np.min(stats,axis = 0)

array([1, 2, 3, 4])

In [71]:
np.min(stats,axis = 1)

array([1, 5])

In [72]:
np.sum(stats)

36

In [73]:
np.sum(stats,axis = 0)

array([ 6,  8, 10, 12])

In [74]:
# Reorganizing Arrays

In [75]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

after1 = before.reshape((2,2,2))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [76]:
# vertically stacking vectors

In [77]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [78]:
# Horizantally stacking vectors

In [79]:
np.hstack([v1,v2,v1])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

In [80]:
# Miscellaneous

In [81]:
#Loading Data from File
filedata = np.genfromtxt('data.txt',delimiter = ',')
filedata

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29.]])

In [82]:
# changing type of data
filedata1 = filedata.astype('int32')
# it generate the copy don't change the type of filedata inplace
filedata1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [83]:
# Boolean Masking and Advanced Indexing
filedata1 > 20

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [84]:
filedata1[filedata1>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [85]:
# you can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [86]:
# any value is greater than any number
np.any(filedata1 > 20,axis = 1)
# horizantol axis

array([False, False,  True])

In [87]:
np.any(filedata1 > 20,axis = 0)
# vertical axis

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [88]:
# if all values are greater than any number
np.all(filedata1 > 10 ,axis = 0)
# vertical axis

array([False, False, False, False, False, False, False, False, False])

In [89]:
(filedata > 5) & (filedata<15)

array([[False, False, False, False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [90]:
~((filedata > 5) & (filedata<15))

array([[ True,  True,  True,  True,  True, False, False, False, False],
       [False, False, False, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])